# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: |
          echo "COLOR=blue" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "The selected color is ${{ steps.color-selector.outputs.COLOR }}"
    
        
  producer:
    runs-on: ubuntu-latest
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
          echo "VARIABLE_NAME=VALUE" >> "$GITHUB_OUTPUT"
    outputs:
      VARIABLE_NAME: ${{ steps.sentence_maker.outputs.VARIABLE_NAME }}

  consumer:
    runs-on: ubuntu-latest
    needs: producer
    env:
      message: ${{ needs.producer.outputs.VARIABLE_NAME }}
    steps:
      - name: Print the message
        run: |
          echo $message

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > result.txt
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: result.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: result
      - shell: bash
        run: |
          value=`cat result.txt`
          echo $(expr $value \* 9) 